/*@ begin PerfTuning (
 def build {
  arg build_command = 'gcc -O0';
 }
 def performance_counter {
  arg method = 'basic timer';
  arg repetitions = 10;
 }
 def performance_params {
  param UF[] = range(1,33);
 }

 def input_params {
  param N[] = [1000,10000000];
 }

 def input_vars {
  decl static double y[N] = random;
  decl double a1 = random;
  decl double a2 = random;
  decl double a3 = random;
  decl double a4 = random;
  decl static double x1[N] = random;
  decl static double x2[N] = random;
  decl static double x3[N] = random;
  decl static double x4[N] = random;
 }

 def search {
  arg algorithm = 'Exhaustive';
 }
) @*/
if ((N<=1000)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [5.08e-06, 4.483e-06, 4.096e-06, 4.096e-06, 4.063e-06, 4.037e-06, 4.042e-06, 4.083e-06, 4.064e-06, 4.054e-06] 
Tuned for specific problem sizes: 
  N = 1000 
Best performance parameters: 
  UF = 6 
--**/


int i;

/*@ begin Loop ( 
    transform Unroll(ufactor=UF) 
    for (i=0; i<=N-1; i++)
    y[i] = a1*x1[i] * a2*x2[i] - a3*x3[i] - a4*x4[i];
) @*/
for (int loop_loop_38=0; loop_loop_38 < 1; loop_loop_38++)  {
    int i;
    for (i = 0; i <= N - 6; i = i + 6) {
      y[i] = a1 * x1[i] * a2 * x2[i] - a3 * x3[i] - a4 * x4[i];
      y[(i + 1)] = a1 * x1[(i + 1)] * a2 * x2[(i + 1)] - a3 * x3[(i + 1)] - a4 * x4[(i + 1)];
      y[(i + 2)] = a1 * x1[(i + 2)] * a2 * x2[(i + 2)] - a3 * x3[(i + 2)] - a4 * x4[(i + 2)];
      y[(i + 3)] = a1 * x1[(i + 3)] * a2 * x2[(i + 3)] - a3 * x3[(i + 3)] - a4 * x4[(i + 3)];
      y[(i + 4)] = a1 * x1[(i + 4)] * a2 * x2[(i + 4)] - a3 * x3[(i + 4)] - a4 * x4[(i + 4)];
      y[(i + 5)] = a1 * x1[(i + 5)] * a2 * x2[(i + 5)] - a3 * x3[(i + 5)] - a4 * x4[(i + 5)];
    }
    for (i = N - ((N - (0)) % 6); i <= N - 1; i = i + 1) 
      y[i] = a1 * x1[i] * a2 * x2[i] - a3 * x3[i] - a4 * x4[i];
  }
/*@ end @*/

} else if ((N<=10000000)) {

/**-- (Generated by Orio) 
Best performance cost: 
  [0.0391229, 0.0388473, 0.0393227, 0.0385319, 0.0387012, 0.0385918, 0.0385511, 0.0390209, 0.0385266, 0.0389517] 
Tuned for specific problem sizes: 
  N = 10000000 
Best performance parameters: 
  UF = 8 
--**/


int i;

/*@ begin Loop ( 
    transform Unroll(ufactor=UF) 
    for (i=0; i<=N-1; i++)
    y[i] = a1*x1[i] * a2*x2[i] - a3*x3[i] - a4*x4[i];
) @*/
for (int loop_loop_38=0; loop_loop_38 < 1; loop_loop_38++)  {
    int i;
    for (i = 0; i <= N - 8; i = i + 8) {
      y[i] = a1 * x1[i] * a2 * x2[i] - a3 * x3[i] - a4 * x4[i];
      y[(i + 1)] = a1 * x1[(i + 1)] * a2 * x2[(i + 1)] - a3 * x3[(i + 1)] - a4 * x4[(i + 1)];
      y[(i + 2)] = a1 * x1[(i + 2)] * a2 * x2[(i + 2)] - a3 * x3[(i + 2)] - a4 * x4[(i + 2)];
      y[(i + 3)] = a1 * x1[(i + 3)] * a2 * x2[(i + 3)] - a3 * x3[(i + 3)] - a4 * x4[(i + 3)];
      y[(i + 4)] = a1 * x1[(i + 4)] * a2 * x2[(i + 4)] - a3 * x3[(i + 4)] - a4 * x4[(i + 4)];
      y[(i + 5)] = a1 * x1[(i + 5)] * a2 * x2[(i + 5)] - a3 * x3[(i + 5)] - a4 * x4[(i + 5)];
      y[(i + 6)] = a1 * x1[(i + 6)] * a2 * x2[(i + 6)] - a3 * x3[(i + 6)] - a4 * x4[(i + 6)];
      y[(i + 7)] = a1 * x1[(i + 7)] * a2 * x2[(i + 7)] - a3 * x3[(i + 7)] - a4 * x4[(i + 7)];
    }
    for (i = N - ((N - (0)) % 8); i <= N - 1; i = i + 1) 
      y[i] = a1 * x1[i] * a2 * x2[i] - a3 * x3[i] - a4 * x4[i];
  }
/*@ end @*/

}
/*@ end @*/

